- hosts: re_master:re_nodes
  gather_facts: False
  roles:
    - setup-connections
- hosts: re_master:re_nodes
  gather_facts: True
  become: yes
  become_user: root
  become_method: sudo
  pre_tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
        disablerepo: rhui-rhel-7-server-dotnet-rhui-debug-rpms,rhui-rhel-7-server-dotnet-rhui-rpms,rhui-rhel-7-server-dotnet-rhui-source-rpms,rhui-rhel-7-server-rhui-debug-rpms,rhui-rhel-7-server-rhui-extras-debug-rpms,rhui-rhel-7-server-rhui-extras-rpms,rhui-rhel-7-server-rhui-extras-source-rpms,rhui-rhel-7-server-rhui-optional-debug-rpms,rhui-rhel-7-server-rhui-optional-rpms,rhui-rhel-7-server-rhui-optional-source-rpms,rhui-rhel-7-server-rhui-rh-common-debug-rpms,rhui-rhel-7-server-rhui-rh-common-rpms,rhui-rhel-7-server-rhui-rh-common-source-rpms,rhui-rhel-7-server-rhui-rpms,rhui-rhel-7-server-rhui-source-rpms,rhui-rhel-7-server-rhui-supplementary-debug-rpms,rhui-rhel-7-server-rhui-supplementary-rpms,rhui-rhel-7-server-rhui-supplementary-source-rpms,rhui-rhel-server-rhui-rhscl-7-debug-rpms,rhui-rhel-server-rhui-rhscl-7-rpms,rhui-rhel-server-rhui-rhscl-7-source-rpms
  roles:
    - redis-enterprise
