- name: Creating datagen connector
  uri:
    url: "{{connect_endpoint}}/connectors"
    method: POST
    return_content: yes
    validate_certs: no
    follow_redirects: all
    body: "{{ lookup('template','datagen-pageviews-body.j2') }}"
    body_format: json
    headers:
        Content-Type: "application/json"
  ignore_errors: true

- name: Creating redis sink connector
  uri:
    url: "{{connect_endpoint}}/connectors"
    method: POST
    return_content: yes
    validate_certs: no
    follow_redirects: all
    body: "{{ lookup('template','redis-sink-json.j2') }}"
    body_format: json
    headers:
        Content-Type: "application/json"
  ignore_errors: true
