- name: install confluent key
  become: yes
  shell:
    cmd:  wget -qO - https://packages.confluent.io/deb/7.5/archive.key | sudo apt-key add -

- name: add repository
  become: yes
  shell:
    cmd:  add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/7.5 stable main" -y
  ignore_errors: yes

# - name: add repository
#   become: yes
#   shell:
#     cmd:  add-apt-repository "deb https://packages.confluent.io/clients/deb $(lsb_release -cs) main" -y
#   ignore_errors: true

- name: update apt-get
  become: yes
  shell:
    cmd: apt-get update
  ignore_errors: true

- name: add confluent platform	
  become: yes
  shell:
    cmd: apt-get install confluent-platform -y
  ignore_errors: true

- name: fix  var log kafka permission for kafka connect 
  become: yes
  shell:
    cmd: chmod 770 /var/log/kafka
  ignore_errors: yes
