- name: confluent install
  include_tasks: confluent-install.yml
  when:
    - install_confluent|bool
- name: confluent property file cretion
  include_tasks: confluent-properties.yml
  when:
    - create_confluent_properties|bool
- name: confluent start
  include_tasks: confluent-start.yml
  when:
    - start_confluent|bool
- name: add confluent plug-ins
  include_tasks: confluent-connect-plug.yml
  when:
    - plugin_confluent|bool
- name: add confluent connectors
  include_tasks: confluent-add-connectors.yml
  when:
    - add_connectors|bool
