- name: Get the IPs
  set_fact:
    ip_ext_node: "{{ inventory_hostname }}"
    ip_int_node: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: save external ip
  copy:
    content: "{{ ip_ext_node }}"
    dest: kafka_external_ip.txt

- name: save external ip locally
  fetch:
    dest: temp/
    src: kafka_external_ip.txt
    flat: yes

- name: save internal ip
  copy:
    content: "{{ ip_int_node }}"
    dest: kafka_internal_ip.txt

- name: save internal ip locally
  fetch:
    dest: temp/
    src: kafka_internal_ip.txt
    flat: yes

- name: confluent install
  include_tasks: confluent-install.yml
  when:
    - install_confluent|bool
#  must happen before confluent connect is started or plugins won't be usable until connect restart
- name: add confluent plug-ins
  include_tasks: confluent-connect-plug.yml
  when:
    - plugin_confluent|bool

- name: confluent property file cretion
  include_tasks: confluent-properties.yml
  when:

    - create_confluent_properties|bool
- name: confluent start
  include_tasks: confluent-start.yml
  when:
    - start_confluent|bool

- name: wait until connect is acive
  become: yes
  command: curl -X GET "{{connect_endpoint}}"
  retries: 20
  delay: 10
  register: result
  until: result.rc == 0

- name: add confluent connectors
  include_tasks: confluent-add-connectors.yml
  when:
    - add_connectors|bool
