- meta: end_play
  when: skipping_tester|bool

- name: Get the IPs
  set_fact:
    ip_ext_node: "{{ inventory_hostname }}"
    ip_int_node: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: save external ip
  copy:
    content: "{{ ip_ext_node }}"
    dest: tester_external_ip.txt

- name: save external ip locally
  fetch:
    dest: temp/
    src: tester_external_ip.txt
    flat: yes

- name: save internal ip
  copy:
    content: "{{ ip_int_node }}"
    dest: tester_internal_ip.txt

- name: save internal ip locally
  fetch:
    dest: temp/
    src: tester_internal_ip.txt
    flat: yes

- name: install redis tools
  include_tasks: install-redis-tools.yml
  when:
    - install_redis_tools|bool

- name: add github repositories
  include_tasks: add-github-repos.yml
  when:
    - add_github_repos|bool

- name: install java maven and go
  include_tasks: install-java-maven-go.yml
  when:
    - install_java_maven_go|bool

