---
enable_volumes: "{{ ENABLE_VOLUMES|default(true)|bool }}"
enable_flash: "{{ ENABLE_FLASH|default(true)|bool }}"
s3_re_binary: "{{ S3_RE_BINARY }}"

deb_packages:
  - jq
  - tree
  - sysstat
  - iputils-ping
  - libcap2-bin 
  - build-essential
  - autoconf
  - automake
  - libbsd-dev
  - libltdl-dev
  - libtool
  - libpcre3-dev 
  - libevent-dev
  - pkg-config
  - zlib1g-dev
  - libssl-dev
  - ntp
