---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes


  pre_tasks:
    - name: Update yum packages
      yum: 
        name: '*'
        state: latest
        disablerepo: rhui-rhel-7-server-dotnet-rhui-debug-rpms,rhui-rhel-7-server-dotnet-rhui-rpms,rhui-rhel-7-server-dotnet-rhui-source-rpms,rhui-rhel-7-server-rhui-debug-rpms,rhui-rhel-7-server-rhui-extras-debug-rpms,rhui-rhel-7-server-rhui-extras-rpms,rhui-rhel-7-server-rhui-extras-source-rpms,rhui-rhel-7-server-rhui-optional-debug-rpms,rhui-rhel-7-server-rhui-optional-rpms,rhui-rhel-7-server-rhui-optional-source-rpms,rhui-rhel-7-server-rhui-rh-common-debug-rpms,rhui-rhel-7-server-rhui-rh-common-rpms,rhui-rhel-7-server-rhui-rh-common-source-rpms,rhui-rhel-7-server-rhui-rpms,rhui-rhel-7-server-rhui-source-rpms,rhui-rhel-7-server-rhui-supplementary-debug-rpms,rhui-rhel-7-server-rhui-supplementary-rpms,rhui-rhel-7-server-rhui-supplementary-source-rpms,rhui-rhel-server-rhui-rhscl-7-debug-rpms,rhui-rhel-server-rhui-rhscl-7-rpms,rhui-rhel-server-rhui-rhscl-7-source-rpms
    - name: create re home dir
      file:
        state: directory
        path: "/redis"

  tasks:
    - name: create download directory
      file:
        state: directory
        path: "/var/tmp/re-download"
    - name: Unarchive software
      unarchive: 
        src: "https://s3.amazonaws.com/redis-enterprise-software-downloads/6.2.12/redislabs-6.2.12-68-rhel7-x86_64.tar"
        dest: /var/tmp/re-download
        remote_src: yes
    - name: Install the software
      command: "./install.sh -y"
      args:
        chdir: /var/tmp/re-download
        creates: /var/opt/redislabs/log/rlcheck.log
    - name: chown redis dir filesystem
      file:
       dest: /redis
       owner: redislabs
       group: redislabs
       recurse: yes
