confluent_version: '7.5.1'
confluent_folder: '7.5'
installation_dir : /opt
username: "{{ansible_user}}"
install_confluent: true
create_confluent_properties: true
start_confluent: true
use_hostname: kafka
